"""
Django settings for inticure_backend project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from re import template

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h4q4vc2$!z^0z5qo^fi3q25b(f$5s-r*bi+fzw108-dymj0(je'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS =['*']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = ['*']
# Application definition
CSRF_TRUSTED_ORIGINS = [
    'https://inticure.com',
    'https://admin.inticure.com',
    'https://analysis.inticure.com',
    'https://customers.inticure.com',
    'https://doctor.inticure.com',
    'https://inticure.online',
    'https://admin.inticure.online',
    'https://analysis.inticure.online',
    'https://customers.inticure.online',
    'https://doctor.inticure.online',
]


SESSION_COOKIE_AGE = 60 * 60 * 24 * 90  # 90 days in seconds

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SECURE = True

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'analysis',
    'doctor',
    'common',
    'customer',
    'administrator',
    'django_cron'
]
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'inticure_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inticure_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'inticure',
        'USER': 'root',
        'PASSWORD': 'PHW#84#jeor',
        'HOST': 'localhost',
        'PORT': '3306',
    }
    
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'inticure',
    #     'USER': 'inticure',
    #     'PASSWORD':'inticure',
    #     'HOST': 'mysql',
    #     'PORT': '3306',
    # }
    
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

RAZORPAY_API_KEY='rzp_live_eQW1QMaOrh8ew2'
RAZORPAY_API_SECRET='v80oY9rr7MrkcAwGvylaIfla'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # This should point to the static folder
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#     )
# }

# Twilio SendGrid
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = "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"
# EMAIL_HOST_PASSWORD = "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"

# Stripe keys

STRIPE_PUBLISHABLE_KEY = 'pk_test_51M5C95SCODPataddX2b5ysBUt1ok9edcDSdTkMxBzbgCm2IBrKLFyL2FbFn6nBCLeWG5wRdCd2eJcUniEFGXuuRt00sMzyQaYH'
STRIPE_SECRET_KEY = 'sk_test_51M5C95SCODPataddVC2wHyNJTO5SYEI1KP6HZtgdqACj7fQj7OxkYVqANlBWwhzbCN6nIccDvLQcq4mbe6ktVohG001uTpOqZe'

# STRIPE_PUBLISHABLE_KEY = 'pk_live_51M1OkdSF4WUBrc54crSYbWl5CXbId3btRzGZGkTbx2sWs84EqBgdla7PW5uXlKghwiz7n8szMlZ1KmtKF3kdcpg700HUM0GIoU'
# STRIPE_SECRET_KEY = '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'

TWILIO_ACCOUNT_SID = "AC148221a87fe05c4f45b76f8e4e8e39c7"
TWILIO_AUTH_TOKEN = "84425555ec44e0227bd21b60bc119902"
TWILIO_WHATSAPP_NUMBER = 'whatsapp:+14155238886'
# TWILIO_NOTIFY_SID = "IS62f6a8afa05bf5b99f8d2458196ba1f3"
TWILIO_NUMBER = "+1205890-2416"
# TWILIO_WHATSAPP_NUMBER = "whatsapp:+971506128542"
# BASE_URL = "127.0.0.1:8000"
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar_Full': [
#             ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
#             ['Link', 'Unlink', 'Anchor'],
#             ['Image', 'Flash', 'Table', 'HorizontalRule'],
#             ['TextColor', 'BGColor'],
#             ['Smiley', 'SpecialChar'], ['Source'],
#             ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
#             ['NumberedList', 'BulletedList'],
#             ['Indent', 'Outdent'],
#             ['Maximize'],
#         ],
#         'extraPlugins': 'justify,liststyle,indent',
#     },
# }

CRON_CLASSES = [
    'common.cron.SendEmails',
]

